  finally:
    - name: buildah
      taskRef:
        kind: Task
        name: buildah
      params:
        - name: IMAGE
          value: 'docker.io/your-username/your-image:latest' # Replace with your image reference
        - name: BUILDER_IMAGE
          value: 'quay.io/buildah/stable:v1'
        - name: STORAGE_DRIVER
          value: overlay
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: ''
        - name: PUSH_EXTRA_ARGS
          value: ''
        - name: SKIP_PUSH
          value: 'false'
        - name: BUILD_ARGS
          value:
            - ''

    - name: deploy
      taskRef:
        kind: Task
        name: deploy
      params:
        - name: app-name
          value: 'your-app-name' # Replace with your application name
        - name: build-image
          value: 'docker.io/your-username/your-image:latest' # Replace with your image reference
      workspaces:
        - name: source
          workspace: output

    - name: openshift-client
      taskRef:
        kind: Task
        name: openshift-client
      params:
        - name: script
          value: |
            oc create deployment $(params.app-name) --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -
      workspaces:
        - name: source
          workspace: output